# Konfiguracja budowania dla Netlify
[build]
  # Uruchom komendę z głównego folderu repozytorium
  command = "npm run build"

  # OPUBLIKUJ FOLDER "dist" (ZGODNIE Z vite.config.ts)
  publish = "dist"

# Reguła przekierowania dla aplikacji typu Single Page Application (SPA).
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Opcjonalne nagłówki
[[headers]]
  for = "/*"
  [headers.values]
  Vary = "Accept-Encoding"